### ISSUE TITLE
Problème lorsque l'on ajoute un fichier .cnstr dans le fichier .vmtf

### ISSUE THREAD

**Issue by rkouakou06** [sgsokol/influx#7]
Bonjour,
Lorsque j'effectue une simulation Influx_s avec les fichiers contenus dans le dossier ci-joint ( [test_mtf_RKO.zip](https://github.com/sgsokol/influx/files/14421054/test_mtf_RKO.zip) ), j'obtiens une erreur comme celle-ci : 

Traceback (most recent call last):
  File "C:\Users\kouakou\AppData\Local\miniconda3\envs\influx\Scripts\influx_s-script.py", line 5, in <module>
    from influx_si.cli import cli
  File "C:\Users\kouakou\AppData\Local\miniconda3\envs\influx\lib\site-packages\influx_si\cli.py", line 10, in <module>
    res=exec(open(s).read())
  File "<string>", line 441, in <module>
  File "C:\Users\kouakou\AppData\Local\miniconda3\envs\influx\Scripts\txt2ftbl.py", line 1464, in main
    dsec,dclen,dfdef=compile(rmtf, cmd)
  File "C:\Users\kouakou\AppData\Local\miniconda3\envs\influx\Scripts\txt2ftbl.py", line 1018, in compile
    pth=try_ext(mtf["cnstr"], ["cntsr", "tsv", "txt"])
  File "C:\Users\kouakou\AppData\Local\miniconda3\envs\influx\Scripts\txt2ftbl.py", line 135, in try_ext
    raise Exception(f"try_ext: not found file '{f}' neither literal nor with extensions: '"+"', '".join(li)+"'")
Exception: try_ext: not found file 'design_test_1' neither literal nor with extensions: 'cntsr', 'tsv', 'txt'
Traceback (most recent call last):
  File "u:\Projet\IsoDesign\isodesign\process\calculation.py", line 499, in <module>
    test_object2.influx_simulation()
  File "u:\Projet\IsoDesign\isodesign\process\calculation.py", line 459, in influx_simulation
    subprocess.run(["influx_s", "--prefix", prefix, "--mtf", f"{prefix}.vmtf", "--noopt"], shell=True, check=True)
  File "C:\Program Files\Python310\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['influx_s', '--prefix', 'design_test_1', '--mtf', 'design_test_1.vmtf', '--noopt']' returned non-zero exit status 1.

L'extension de mon fichier design_test_1.cnstr n'est pas reconnue dans le fichier vmtf comme l'atteste le traceback ici : 

File "C:\Users\kouakou\AppData\Local\miniconda3\envs\influx\Scripts\txt2ftbl.py", line 135, in try_ext
    raise Exception(f"try_ext: not found file '{f}' neither literal nor with extensions: '"+"', '".join(li)+"'")
Exception: try_ext: not found file 'design_test_1' neither literal nor with extensions: 'cntsr', 'tsv', 'txt'.  

Lorsque j'effectue la simulation influx_s en enlevant mon fichier design_test_1.cnstr du fichier vmtf, la simulation fonctionne mais lorsqu'il est inclut dans le fichier .vmtf, j'obtiens cette erreur.

Il semblerait qu'il y ai une faute de frappe qui a pour conséquence que l'extension cnstr n'est pas détecté mais plutôt l'extension "cntsr".

**Comment by sgsokol** [comment]
Thanks for reporting and fix suggestion. It was it. This bug will be corrected in the next v7.0.2 release.
