### ISSUE TITLE
Error when launching influx with subprocess

### ISSUE THREAD

**Issue by llegregam** [sgsokol/influx#8]
While working on a project that uses influx_si to run simulations, I get this error when I launch the tool using a subprocess in my code:
`FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable
Traceback (most recent call last):
  File "C:\Users\legregam\PycharmProjects\IsoDesign\isodesign\process\calculation.py", line 439, in <module>
    test.main(mix1)
  File "C:\Users\legregam\PycharmProjects\IsoDesign\isodesign\process\calculation.py", line 359, in main
    self.influx_simulation()
  File "C:\Users\legregam\PycharmProjects\IsoDesign\isodesign\process\calculation.py", line 351, in influx_simulation
    subprocess.run(["influx_s", "--prefix", self.prefix, "--mtf", f"{self.prefix}.vmtf", "--noopt"], check=True)
  File "C:\Users\legregam\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['influx_s', '--prefix', 'design_test_1', '--mtf', 'design_test_1.vmtf', '--noopt']' returned non-zero exit status 1.
`

All the necessary files are present when running the tool. I thus switched to trying to launch influx_s through the main function:
`influx_s.main(["--prefix", self.prefix, "--mtf", f"{self.prefix}.vmtf", "--noopt"])`

But this time I get another error:
`Traceback (most recent call last):
  File "C:\Users\legregam\PycharmProjects\IsoDesign\isodesign\process\calculation.py", line 439, in <module>
    test.main(mix1)
  File "C:\Users\legregam\PycharmProjects\IsoDesign\isodesign\process\calculation.py", line 359, in main
    self.influx_simulation()
  File "C:\Users\legregam\PycharmProjects\IsoDesign\isodesign\process\calculation.py", line 350, in influx_simulation
    influx_s.main(["--prefix", self.prefix, "--mtf", f"{self.prefix}.vmtf", "--noopt"])
  File "C:\Users\legregam\PycharmProjects\IsoDesign\venv\Lib\site-packages\influx_si\influx_s.py", line 207, in main
    raise Exception("""Cannot determine wether we are in 's' or 'i' case.
Exception: Cannot determine wether we are in 's' or 'i' case.
    My basename must start with 'influx_s' or 'influx_i' instead of 'calculat'.`

I checked in influx's main function, and I added a print of this variable 'me' to see why it couldn't understand the basename referenced in the error:

    global me
    # my own name
    me=os.path.realpath(sys.argv[0])
    # my install dir
    dirinst=os.path.dirname(os.path.realpath(influx_si.__file__))
    dirbin=os.path.join(dirinst, "bin")
    print(me) # Here is my added line
    me=os.path.basename(me)

The me variable contains the math to my module being executed and not influx's module:
C:\Users\legregam\PycharmProjects\IsoDesign\isodesign\process\calculation.py

Any idea how to correct these bugs?

**Comment by sgsokol** [comment]
The bug in determining 'me' variable will be fixed in v7.0.3.
As to lacking file, I don't have sufficient elements to reproduce this error. What version of isodesign was used? On what input?
